language: java
jdk: oraclejdk8

install: "pip install -r requirements.txt"

before_script:
  - echo 'testing coming soon'

script:
  - "java ./gradlew clean jar"
  # - find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address

branches:
  only:
   - master
   - development
