language: java
dist: trusty

sudo: require
services:
  - docker

env:
  - JDK_USED=9
  #-JDK_USED=openjdk9

script:
  - docker build -t seo80/seo80-docker-repo:jdk$JDK_USED --build-arg JDK_VERSION="openjdk:$JDK_USED"
  - docker images
