language: java
jdk:
  - oraclejdk9
  
env:
  - COVERAGE=0.3

before_install:
  - pwd
  - ls -la

install:
  - ./gradlew clean jar

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

before_deploy:
  - ./gradlew test jacocoTestCoverageVerification

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true
