language: java
jdk: oraclejdk9

install:
  - ./gradlew clean jar

script:
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
