sudo: required
language: java
jdk: oraclejdk8
dist: trusty

install:
  - "./gradlew clean jar"

script:
  - "./gradlew test"

after_success:
  - "./gradlew jacocoTestReport"
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}