language: java
jdk: openjdk8

script:
  - COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/service/cart check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/service/user check

  - COVERAGE=0.35 ./gradlew -p ./monolithic/repository/order check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/cart check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/product check
  - COVERAGE=0.34 ./gradlew -p ./monolithic/repository/user check
