language: java
jdk: oraclejdk8
dist: trusty

env:
  - COVERAGE=0.3

install:
  - ./gradlew clean jar

script:
  - ./gradlew test

after_sucess:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true