language: java
dist: trusty

sudo: require
services:
  - docker

env:
  - JDK_USED=9
  #- JDK_USED=8

script:
  - docker build -t seo80/seo80-docker-repo:jdk$JDK_USED --build-arg JDK_VERSION="openjdk:$JDK_USED" .
  - docker run --rm seo80/seo80-docker-repo:jdk$JDK_USED ./gradlew clean jar

stages:
  - test
  - coverage

jobs:
  include:
    - stage: coverage
      name: "Coverage ui-check JAVA 9"
      intall: skip
      script:
        - docker run --rm seo80/seo80-docker-repo:jdk$JDK_USED /bin/bash -c "$GRADLE_CHECK"
      env:
        - JDK_USED=9
        - COVERAGE_VALUE=0.5
        - GRADLE_CHECK="COVERAGE=$COVERAGE_VALUE ./gradlew -p ./monolithic/ui check"
    - stage: coverage
      name: "Coverage order-check JAVA 9"
      intall: skip
      script:
        - docker run --rm seo80/seo80-docker-repo:jdk$JDK_USED /bin/bash -c "$GRADLE_CHECK"
      env:
        - JDK_USED=9
        - COVERAGE_VALUE=0.24
        - GRADLE_CHECK="COVERAGE=$COVERAGE_VALUE ./gradlew -p ./monolithic/repository/order check"

  deploy:
  provider: script
  script: bash echo 'WIP'
