dist: trusty
language: java
jdk:
  - oraclejdk8
  - oraclejdk9

env:
  - COVERAGE=0.5 TARGET='./monolithic/ui'
  - COVERAGE=0.5 TARGET='./monolithic/service/cart'
  - COVERAGE=0.5 TARGET='./monolithic/service/user'
  - COVERAGE=0.3 TARGET='./monolithic/repository/order'
  - COVERAGE=0.5 TARGET='./monolithic/repository/cart'
  - COVERAGE=0.5 TARGET='./monolithic/repository/product'
  - COVERAGE=0.3 TARGET='./monolithic/repository/user'

before_script:
  - ./gradlew clean jar

script:
  - ./gradlew -p $TARGET check

after_success:
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: echo 'WIP'
  skip_cleanup: true
  on:
    all_branches: true
