language: java
jdk: openjdk10

os: linux

services:
  - docker

env:
  - COVERAGE=.10

script:
  - travis encrypt DOCKER_PASSWORD="secretvalue" --ad env.global --com
  - ./gradlew clean jar

jobs:
  include:
    - stage: test
      script: ./gradlew -p ./monolithic/ui check
      script: ./gradlew -p ./monolithic/service/cart check
      script: ./gradlew -p ./monolithic/service/user check
      script: ./gradlew -p ./monolithic/repository/order check
      script: ./gradlew -p ./monolithic/repository/cart check
      script: ./gradlew -p ./monolithic/repository/product check
      script: ./gradlew -p ./monolithic/repository/user check
    - stage: deploy
      script: echo 'WIP'
