language: java
jdk: openjdk8
dist: trusty

sudo: require
services:
  - docker

env:
  - GRADLE_TARGET="./gradlew test && ./gradlew jacocoTestReport && find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print \$3\" \"\$4\" \"\$5}'"
  - GRADLE_TARGET="./gradlew test jacocoTestCoverageVerification"


before_install:
  - docker pull seo80/seo80-docker-repo:latest

script:
  - docker run --rm seo80/seo80-docker-repo:latest /bin/bash -c $GRADLE_TARGET

deploy:
  - set -x -v;
    set -e;
    echo "WIP"
    set +x +v;
