language: java
jdk: oraclejdk8
env:
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/ui
  - COVERAGE=0.397 TEST_TARGET=./monolithic/repository/cart
  - COVERAGE=0.124 TEST_TARGET=./monolithic/repository/user
  - COVERAGE=0.148 TEST_TARGET=./monolithic/service/order
  - COVERAGE=0.148 TEST_TARGET=./monolithic/service/cart
  - COVERAGE=0.148 TEST_TARGET=./monolithic/service/product
  - COVERAGE=0.148 TEST_TARGET=./monolithic/service/user

  - COVERAGE=0.35 ./gradlew test jacocoTestCoverageVerification

script:
  - ./gradlew clean jar
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/dists/

    stages:
      - test
    jobs:
      include:
        - stage: test
          name: unit-test
          install: skip
          script:
            - ./gradlew $TEST_TARGET check
        -stage: deploy
          script:
            -  bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\"
            --password-stdin ;"	    --password-stdin ;"
          on:
            all_branches: true
