language: java
jdk: oraclejdk9

script:
  - ./gradlew clean jar

after_success:
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
  - COVERAGE=0.31 ./gradlew jacocoTestCoverageVerification

deploy:
  provider: script
  script: echo 'WIP'
