language: java
jdk:
  - oraclejdk8
  #- oraclejdk9
dist: trusty

env:
  matrix:
  - COVERAGE=0.057 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.148 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.362 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.124 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.318 BUILD_TARGET=./monolithic/repository/user
  
  
install:
  - ./gradlew clean jar

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./gradlew -p $BUILD_TARGET check

deploy:
  provider: script
  script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  on:
    all_branches: true