language: java
jdk: openjdk10

script:
  - ./gradlew clean jar

after_success:
  - echo 'testing'
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
