language: java
dist: trusty
jdk:
  - oraclejdk8
env:
  - TESTFOLDER=./monolithic/ui
  - TESTFOLDER=./monolithic/service/cart
  - TESTFOLDER=./monolithic/service/user
  - TESTFOLDER=./monolithic/repository/order
  - TESTFOLDER=./monolithic/repository/cart
  - TESTFOLDER=./monolithic/repository/product
  - TESTFOLDER=./monolithic/repository/user
  - COV=0.5
  - COV=0.24
  - COV=0.10
install:
  - ./gradlew clean jar

script:
  - "COVERAGE=0.5 ./gradlew -p $TESTFOLDER check"


deploy:
  - provider: script
    script: deploy_production.sh
    on:
      branch: final_step4_test-deploy
