sudo: enabled
language: java
jdk: oraclejdk8
os: linux
dist: trusty
install:
  - ./gradlew clean jar
script:
  - ./gradlew test
  - ./gradlew jacocoTestCoverageVerification
after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true
