sudo: enabled
language: java
os: linux
dist: trusty
stages:
  - build
  - test
jobs:
  include:
    - stage: test
      name: "Test UI"
      jdk:
        - oraclejdk8
        - oraclejdk9
      install: ./gradlew clean jar
      script:
        - ./gradlew -p ./monolithic/ui check
      env:
        - COVERAGE=1.0
    - stage: test
      name: "Test Servce Cart"
      jdk:
        - oraclejdk8
        - oraclejdk9
      install: ./gradlew clean jar
      script:
        - ./gradlew -p ./monolithic/service/cart check
      env:
        - COVERAGE=1.0
    - stage: test
      name: "Test Service User"
      jdk:
        - oraclejdk8
        - oraclejdk9
      install: ./gradlew clean jar
      script:
        - ./gradlew -p ./monolithic/service/user check
      env:
        - COVERAGE=0.5
    - stage: test
      name: "Test Repository Order"
      jdk:
        - oraclejdk8
        - oraclejdk9
      install: ./gradlew clean jar
      script:
        - ./gradlew -p ./monolithic/repository/order check
      env:
        - COVERAGE=0.0
    - stage: test
      name: "Test Repository Cart"
      jdk:
        - oraclejdk8
        - oraclejdk9
      install: ./gradlew clean jar
      script:
        - ./gradlew -p ./monolithic/repository/cart check
      env:
        - COVERAGE=1.0
    - stage: test
      name: "Test Repository Product"
      jdk:
        - oraclejdk8
        - oraclejdk9
      install: ./gradlew clean jar
      script:
        - ./gradlew -p ./monolithic/repository/product check
      env:
        - COVERAGE=1.0
    - stage: test
      name: "Test Repository User"
      jdk:
        - oraclejdk8
        - oraclejdk9
      install: ./gradlew clean jar
      script:
        - ./gradlew -p ./monolithic/repository/user check
      env:
        - COVERAGE=0.0
after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true
