language: java
jdk:
- openjdk10
- oraclejdk9
services:
- docker
env:
  matrix:
  - COVERAGE=0.057 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.148 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.36 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.124 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.318 BUILD_TARGET=./monolithic/repository/user
  global:
  - DOCKER_LOGIN=cen24
  - secure: 
install:
- "./gradlew clean jar"
script:
- "./gradlew -p $BUILD_TARGET check"
after_success:
- "./gradlew jacocoTestReport"
- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

before_deploy:
  - ./gradlew -p ./monolithic/ui packageToContainer

deploy:
  provider: script
  script: chmod +x ./script/deploy.sh && ./script/deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH = master && $BUILD_TARGET = ./monolithic/ui 
