dist: trusty
language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - ./gradlew clean jar 

jdk: 
  - oraclejdk8
  - oraclejdk9

matrix:
  include:
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolithic/ui_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolithic/service/cart_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolithic/service/ui_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolithic/repository/order_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolithic/repository/cart_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolithic/repository/product_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolithic/repository/user_check

after_success:

deploy:
  provider: script
  script: echo `WIP`
  on:
    branch: master
