language: java
jdk: oraclejdk9

script: 
  - ./gradlew clean jar

after_script:
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'