language: java
jdk: openjdk10
env:
  - COVERAGE=.0
script:
  - ./gradlew clean jar
  - echo 'testing'
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - ./gradlew test jacocoTestCoverageVerification

deploy:
  -echo 'WIP'
