language: java
jdk: openjdk8
dist: trusty

sudo: require
services:
  - docker

env:
  global:
  - COVERAGE_VALUE=0.5

  matrix:
  - GRADLE_CHECK="./monolithic/ui check"
  - GRADLE_CHECK="./monolithic/service/cart check"
  - GRADLE_CHECK="./monolithic/service/user check"
  - GRADLE_CHECK="./monolithic/repository/order check"
  - GRADLE_CHECK="./monolithic/repository/cart check"
  - GRADLE_CHECK="./monolithic/repository/product check"
  - GRADLE_CHECK="./monolithic/repository/user check"


before_install:
  - docker pull seo80/seo80-docker-repo:latest

script:
  - docker run --rm seo80/seo80-docker-repo:latest ./gradlew clean jar
  - docker run --rm seo80/seo80-docker-repo:latest COVERAGE=$COVERAGE_VALUE ./gradlew -p $GRADLE_CHECK

deploy:
  provider: script
  script: bash echo 'WIP'
