dist: trusty
language: java
jdk: oraclejdk8
sudo: required	
services:
    - docker
    before_install:
        -docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 
stages:
    - build
    - test
    - deploy
jobs:
    include:
      - stage: build
        name : build
        script:
            - ./gradlew clean jar 
      - stage: test
        name: test
        script:
            - ./gradlew test
        after_success:
            - ./gradlew jacocoTestReport	    
            - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'	    
            - ./gradlew jacocoTestCoverageVerification
      - stage: deploy
        provider: script
        script: echo 'WIP'
        on:
            all_branches: true

