language: java
jdk: openjdk8
dist: trusty

sudo: require
services:
  - docker

before_install:
  - docker pull seo80/seo80-docker-repo:latest

script:
  - docker run --rm seo80/seo80-docker-repo:latest /bin/bash -c "./gradlew test && ./gradlew jacocoTestReport && find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print \$3\" \"\$4\" \"\$5}'"
  - docker run --rm seo80/seo80-docker-repo:latest /bin/bash -c "./gradlew test jacocoTestCoverageVerification"

deploy:
  provider: script
  script: bash echo 'WIP'
