language: java
dist: trusty
jdk:
  - oraclejdk8
env:
  - TESTFOLDER=./monolithic/ui check
  - TESTFOLDER=./monolithic/service/cart check
  - TESTFOLDER=./monolithic/service/user check
  - TESTFOLDER=./monolithic/repository/order check
  - TESTFOLDER=./monolithic/repository/cart check
  - TESTFOLDER=./monolithic/repository/product check
  - TESTFOLDER=./monolithic/repository/user check

install:
  - ./gradlew clean jar

script:
  - "COVERAGE=0.5 ./gradlew -p $TESTFOLDER"


deploy:
  - provider: script
    script: deploy_production.sh
    on:
      branch: final_step4_test-deploy
