language: java
jdk: oraclejdk8

script:
  - ./gradlew build -x signArchives -s

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/dists/

stages:
  - test
jobs:
  include:
    - stage: test
      name: test-not-ready
      install: skip
      script:
       - echo 'testing coming soon’
      