dist: trusty
language: java
jdk: oraclejdk8
env:
    - COVERAGE=0.057 ./gradlew -p ./monolithic/ui check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/cart check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/user check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/order check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/cart check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/product check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/user check

script:
    - ./gradlew clean jar 
after_success:
    - $COVERAGE 
deploy:
    provider: script
    script: echo 'WIP'
    on:
       all_branches: true

