language: java
dist: trusty
jdk:
  - openjdk8

sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

env:
  - TEST_FOLDER=./monolithic/ui
  - TEST_FOLDER=./monolithic/service/cart
  - TEST_FOLDER=./monolithic/service/user
  - TEST_FOLDER=./monolithic/repository/order
  - TEST_FOLDER=./monolithic/repository/cart
  - TEST_FOLDER=./monolithic/repository/product
  - TEST_FOLDER=./monolithic/repository/user

script:
  - ./gradlew clean jar
  - COVERAGE=$COVERAGE ./gradlew -p $TEST_FOLDER check

deploy:
  - provider: script
    script: echo 'WIP'
    #on:
      #branch: master