dist: trusty
language: java
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - ./gradlew clean jar 

matrix:
  include:
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolith/ui_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolith/service/cart_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolith/service/ui_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolith/repository/order_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolith/repository/cart_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolith/repository/product_check
  - env: COVERAGE=0.4
    script: ./gradlew test ./monolith/repository/user_check

after_success:

deploy:
  provider: script
  script: echo `WIP`
  on:
    branch: master
