dist: trusty
language: java
jdk: oraclejdk8
before_script:
    - ./gradlew clean jar 
script:
    - ./gradlew test
after_success:
    - ./gradlew jacocoTestReport
    - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
    - ./gradlew jacocoTestCoverageVerification
deploy:
    provider: script
    script: echo 'WIP'
    on:
       all_branches: true

